### PR TITLE
Tests against logic inversion

### PR DESCRIPTION
**Pull request by bwilkins**
Followup to pr #17

### CODE REVIEW

**Comment by jgarber623** [comment]
Awesome, thanks @bwilkins!

I'm still learning Rspec, so could either you or @MelissaKaulfuss walk me through a couple things? Specifically:

- What does `double(File)` do? Does `double` essentially "mock" or "stub" the thing its passed?
- Is `allow(File).to receive(:open).and_yield(file)` doing what I'd imagine it does based on the plain English-ish syntax?

Thanks again for adding these specs. They're a big help!

**Comment by jgarber623** [comment]
Merged into master at bdb6c4d.

**Comment by jgarber623** [comment]
Looks like I may have answered many of my own questions by [reading the manual](http://rspec.info/documentation/3.5/rspec-mocks/).

😁

**Comment by bwilkins** [comment]
Hey @jgarber623, happy to help 😃

With regards to rspec:
- `double(File)` as you suggested creates a mock of `File`. I can also stub methods at the same time, such as `double(File, write: nil)`, but in this case I wanted the semantics of `allow`. (When using double like this to also create stub/mock methods, double will check if a class has been given and only let you stub methods that actually exist on that class. You can use a string as the first parameter to prevent this.)
- the line `allow(File).to receive(:open).and_yield(file)` is literally stubbing the `.open` method on the File class, and replacing what it would normally do. I don't actually like doing this - if the code being tested changed, for instance if you were to change it to `f = File.open(filename, 'rb')`, the test would break. I would probably prefer to take the concern of file i/o away from the spritebuilder class altogether, so it can just focus on constructing the SVG spritesheet.

Don't be afraid to nest your `describe` blocks, either. `describe` and `context` are functionally equivalent, they really only differ semantically, ie `describe` says "I want to talk about this thing", while `context` says "let's talk about that thing in _this_ situation". Personally, I would normally choose to `describe '#build' do ...`, because I'm wanting to talk about the `#build` method and what it does, and I'll use `context` to talk about the scenarios that I put it in. For svgeez however I followed the choices made by yourself as the author, as it's better for everything to look the same. 😃

**Comment by jgarber623** [comment]
@bwilkins Oh, wow. Thanks so much for the thorough reply! I'll respond with more in the morning (it's late here on the US East Coast).

Regarding `describe` and `context`, is it reasonable to think about it like…

```rb
describe '#build` do
  context 'when a particular condition exists' do
    it 'returns a string' do
      # …
    end
  end
end
```

**Comment by bwilkins** [comment]
That's exactly what I'd normally do 😄

**Pull request closed without merging**
