### PR TITLE
Fixing logic inversion causing svgeez to not work under normal circumstances (jgarber623/svgeez#16)

### PR DESCRIPTION
**Pull request by bwilkins**

### CODE REVIEW

**Comment by bwilkins** [comment]
This fixes #16.

**Comment by jgarber623** [comment]
@bwilkins Thanks for fixing the logic problem.

I really like the text additions as well, but would like to more easily run through them locally before merging. Could you reissue your PR with _just_ the test additions and from a branch named other than `master`?

**Comment by bwilkins** [comment]
Sure thing @jgarber623, I can do that.

**Comment by jgarber623** [comment]
Superseded by #18.

**Pull request closed without merging**
